listen=YES
listen_ipv6=NO

anonymous_enable=NO
local_enable=YES
write_enable=YES

guest_enable=YES
guest_username=www-data
virtual_use_local_privs=YES
user_sub_token=$USER
local_root=/var/www/html

pam_service_name=vsftpd_virtual
chroot_local_user=YES
allow_writeable_chroot=YES

pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110
pasv_address=0.0.0.0

secure_chroot_dir=/var/run/vsftpd/empty

background=NO
seccomp_sandbox=NO
